Контроллер для создания объявлений
SymfonyLearn/MSPrepareDocsRealty pull request #6
Opened 2020-12-15 09:47 UTC by DmitryKirillov

Контроллер реализован как action-oriented с использованием FOSRestBundle.

Пример запроса:

POST .../api/v1/ad

```
{
  "category": "Квартира",
  "address": "Зеленоград, к. 130, кв. 14",
  "description": "Очень просторная двушка",
  "price": 9500000,
  "rooms": 2,
  "area": 54,
  "floor": 3,
  "seller_id": 1
}
```

2020-12-15 21:21 UTC, NickPanda requested changes
Также, я обнаружил, что у нас нет VO для description

2020-12-15 21:21 UTC, NickPanda commented on public/.htaccess
> +# Use the front controller as index file. It serves as a fallback solution when
А зачем .htaccess у нас же в окружение докера используется nginx?

2020-12-15 21:21 UTC, NickPanda commented on src/Controller/CreateAd/v1/Output/AdIsCreatedDTO.php
> +final class AdIsCreatedDTO
А почему AdI**s**CreatedDTO.
может AdI**d**CreatedDTO?

2020-12-15 21:21 UTC, NickPanda commented on composer.json
> +        "sensio/framework-extra-bundle": "^5.6",
А можно прокомментировать выбор этих пакетов?

2020-12-15 21:21 UTC, NickPanda commented on src/Controller/CreateAd/v1/Manager.php
> +        // todo Поля Id и DateCreated должны генерироваться автоматически
А чем создание через DateTimeImmutable не автоматически или о чем речь?

А вот в ID вопрос, как его генерировать, учитывая что он типа int и сюда не подойдет uuid&

2020-12-15 21:21 UTC, NickPanda commented on src/Controller/CreateAd/v1/Controller.php
> +        $view = $this->view($adIsCreatedDTO, 200);
adIsCreatedDTO тут будет просто id Ad, а зачем?

Ааа, стоп, получается в ответ мы возвращаем id созданного объявления

2020-12-15 21:21 UTC, NickPanda commented on .gitignore
> +/import/
насколько знаю можно на локальной машине в git ignore global 
> git config --global core.excludesFile '~/.gitignore'

2020-12-16 06:14 UTC, denis-gol commented on composer.json
> +        "sensio/framework-extra-bundle": "^5.6",
![image](https://user-images.githubusercontent.com/38101819/102311916-c183c680-3f7e-11eb-9ab6-5f8c9c795789.png)
скорее всего, именно поэтому

2020-12-16 06:16 UTC, denis-gol approved these changes

2020-12-16 19:16 UTC, NickPanda approved these changes

2020-12-16 19:17 UTC, merged